[package]
name = "jinvoke_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
jni = "0.19.0"
thiserror = "1.0.31"